# Generated by Django 3.1.3 on 2021-07-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pas', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('contact', models.CharField(max_length=10)),
                ('contact2', models.CharField(max_length=10)),
            ],
        ),
    ]
