# Generated by Django 3.1.3 on 2021-07-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='contact2',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
