# Generated by Django 3.1.3 on 2021-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210707_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
